# Generated by Django 4.1.1 on 2022-10-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_challenge',
            new_name='deliver_finish',
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_time',
            field=models.IntegerField(default=-1),
        ),
    ]
